version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"

  server:
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
