# fly.toml app configuration file generated for yodl-demo on 2023-10-13T19:24:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yodl-demo"
primary_region = "otp"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
